### ISSUE TITLE
Connection lost after sending a notification with MQTT protocol

### ISSUE THREAD

**Issue by NoahRosa** [stm32duino/WiFi-ISM43362-M3G-L44#10]
Hi,
I've tried to run the examples for the B-L475E-IOT01A2, both the PubSubClient and the Adafruit.io using WiFi.
I've run into a problem when I try to send a notification on a topic the board is subscribed to:
if i try to send it just after the board has published something (so when it is still out of the client.loop() function) it gets parsed without any issue (I can even send a lot of messages and the board will still fetch each of them in different iterations of the loop); however if I send the message while the board is executing the client.loop(), it gets stuck for a while and then it loses the connection to the MQTT server until reconnect() function is invoked.
This happened using either [io.adafruit.com](url) or [broker.mqtt-dashboard.com ](url) as MQTT broker, and sending messages from the android applications MyMQTT and MQTT Dash as MQTT clients.
I think the problem might be related to the WiFi module of the board.

Thanks,
Noah

**Comment by fpistm** [comment]
Linked to https://github.com/stm32duino/STM32Examples/issues/9.

**Comment by fpistm** [comment]
https://github.com/stm32duino/STM32Examples/issues/9#issuecomment-446259981

Unfortunately, as the available() always return 1 (the firmware is not able to tell data available or not without read 👎 )  this implies the mqtt client to process each time it check if data is available.
Maybe it could be possible to enhance the client library.
Anyway, nothing could be done in this library as it is linked to WiFi firmware behavior.
