### ISSUE TITLE
WiFiServer stops after five requests

### ISSUE THREAD

**Issue by maker999** [stm32duino/WiFi-ISM43362-M3G-L44#11]
I based a sketch on one of the examples called "WiFiWebServer" but it stops after exactly 5 requests.

**Comment by fpistm** [comment]
Hi @maker999 
could you give more information?
Core version used, lib version, IDE used,  target board and option...
All relevant information helping to support you.

**Comment by maker999** [comment]
Hi @fpistm 
I used the core version v1.1.1 and IoT_Discovery_Board(STM32L475) which has the WiFi_module on it. I use this core_version because I needed another UART(Serial3) for my project and it seems to be not working well in the latest versions. The WiFi_library_version=1.0.2
Arduino_IDE_version = 1.8.5
thank you :)

**Comment by fpistm** [comment]
Could you test with latest core. 1.1.1 is very old (more than one year) and also the latest WiFi libary v1.1.0 which fix some issues

**Comment by maker999** [comment]
Now I tested with the latest core and wifi_lib and still the same situation. exactly after 5 requests it doesn't respond anymore

**Comment by fpistm** [comment]
ok thanks. Will try when got some time

**Comment by ABOSTM** [comment]
Hi @maker999,
Investigation continue internally,
but first analysis show that it is probably an issue with inventek firmware (wifi module). 
At some point it doesn't respond correctly any more to s0/s3 AT command which are used to send data.

**Comment by fpistm** [comment]
Unfortunately, instability comes from Inventek firmware so it cannot be solved in the library.
Until new firmware available I close this issue, it was also reproduced with Cube FW.
