### ISSUE TITLE
UDP server no more working 

### ISSUE THREAD

**Issue by Yannick-Marietti** [stm32duino/WiFi-ISM43362-M3G-L44#12]
The UDP server is no more working on current ISM43362-M3G-L44 firmware.
It was working in the past.
The example "WiFiUDPSendReceiveString" simply freeze at row " Udp.begin(localPort);".
ISM43362-M3G-L44 is not reacting to any incoming UDP string from a remote client.

**Comment by ABOSTM** [comment]
Hi @Yannick-Marietti,
It is true that there is a regression.
Unfortunately, it comes with Wifi module Firmware upgrade:
With the same board, same version of this library
* FW version C3.5.2.3.BETA9
is working fine
* FW version C3.5.2.5.STM
is not working

There is no API update from inventek between those versions,
so it is a firmware issue. There is nothing we can do on our side.
You can still use version C3.5.2.3.BETA9 ... with the consequences of the use of an old version.
