### ISSUE TITLE
error: 'class WiFiClass' has no member named 'disconnect'

### ISSUE THREAD

**Issue by fred-r** [stm32duino/WiFi-ISM43362-M3G-L44#3]
Hi,

when using WiFiST, we cannot call the disconnect API listed here:
https://www.arduino.cc/en/Reference/WiFiDisconnect

Is it possible to add this service?

I'd like to use the WiFi like this:
SPIClass SPI_3(PC12, PC11, PC10);
WiFiClass WiFi(&SPI_3, PE0, PE1, PE8, PB13);
...
status = WiFi.begin(ssid, password);
...
WiFi.disconnect();

Thanks & Regards,

**Comment by LMESTM** [comment]
@fprwi6labs

**Comment by fprwi6labs** [comment]
Hi @fred-r 
I pushed a [PR](https://github.com/stm32duino/WiFi-ISM43362-M3G-L44/pull/4) to add the missing disconnect function.

**Comment by fpistm** [comment]
#4 merged
