### ISSUE TITLE
Cannot connect to AP when security is not WPA2 PSK

### ISSUE THREAD

**Issue by fred-r** [stm32duino/WiFi-ISM43362-M3G-L44#5]
Hi,

I am currently using the following piece of code:
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(ssid, password); 

And with this piece of code I can connect successfully to my mobile phone used as WiFi AP.
The security is set to WPA2 PSK.

But, when I try to connect to my freebox used as WiFi AP it fails with several security schemes:
* WPA (TKIP+AES): fail
* WPA (TKIP): fail
* WPA (AES/CCMP): fail

Thanks & Regards,
Fred

**Comment by ErikIOT** [comment]
I haven't been able to successfully use any of the examples since the last pull. They kind of worked when fprwi6labs had a branch called "dev", but since then nothing has worked for me.

**Comment by fred-r** [comment]
Hi,

I made some more attempts:
1. tried to reduce the length of the key in WPA => no improvement
2. tried with another AP, this time WPA2 + AES: success

So, to sum up, it seems that:
* all my attempts with WPA failed
* WPA2 worked fine in PSK and AES 

Thanks & Regards,
Fred

**Comment by fpistm** [comment]
Hi,
just tested.
Same results. WEP also failed.
Only all WPA2 sec works.

**Comment by fpistm** [comment]
First check:
AT command seems well formed as requested by the manual:
http://www.inventeksys.com/wp-content/uploads/AT_Command_Set_DOC-UM-20035-2.2.pdf
![screenshot-2018-1-19 at_command_set_doc-um-20035-2 2 pdf](https://user-images.githubusercontent.com/20641798/35162794-ad0e904c-fd44-11e7-867f-bf9808032cd6.png)

**Comment by fpistm** [comment]
Hi @fred-r ,
See my comments in #8 
Let me know if it is ok.

**Comment by fpistm** [comment]
WEP is also failed with MBed and Cube.
Seems a firmware issue.
